name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
        run: |
          echo "$PRIVATE_KEY" > key && chmod 600 key
          ssh -o StrictHostKeyChecking=no -i key ${USER}@${HOST} \
          "cd /home/ec2-user/lmanager && \
          sudo chown -R ec2-user:ec2-user . && \
          git config --global --add safe.directory /home/ec2-user/lmanager && \
          git pull && \
          sudo docker system prune -a --volumes -f && \
          sudo docker stop app || true && \
          sudo docker rm app || true && \
          sudo docker build -t app . --no-cache && \
          sudo docker run -d --name app -p 443:443 \
            -v /home/ec2-user/lmanager/uploads:/app/uploads \
            -v /home/ec2-user/keystore.p12:/app/keystore.p12:ro \
            -e JASYPT_ENCRYPTOR_PASSWORD='${JASYPT_ENCRYPTOR_PASSWORD}' app"